const libros = [
    {
        img: 'img/libro1.jpg',
        nombre: 'Your Soul Is a River',
        autor: 'Nikita Gill',
        Precio: 15,
        idioma: 'español',
        categoria: 'categoria2',
        año: 2021,
        id: 1,
    },

    {
        img: 'img/libro2.jpg',
        nombre: 'Sculpture',
        autor: 'Antiquity Taschen',
        Precio: 11,
        idioma: 'español',
        categoria: 'categoria3',
        año: 2022,
        id: 2,
    },

    {
        img: 'img/libro3.jpg',
        nombre: 'Milk and Honey',
        autor: 'Rupi Kaur',
        Precio: 10,
        idioma: 'ingles',
        categoria: 'categoria1',
        año: 2023,
        id: 3,
    },

    {
        img: 'img/libro4.jpg',
        nombre: 'All the letter i should have send',
        autor: 'Rania Naim',
        Precio: 36,
        idioma: 'ingles',
        categoria: 'categoria2',
        año: 2024,
        id: 4,
    },

    {
        img: 'img/libro5.jpg',
        nombre: 'Goal PLanner',
        autor: 'Iki Glop',
        Precio: 8,
        idioma: 'ingles',
        categoria: 'categoria1',
        año: 2024,
        id: 5,
    },

    {
        img: 'img/libro6.jpg',
        nombre: 'The two towers',
        autor: 'J.R.R Tolkien',
        Precio: 30,
        idioma: 'ingles',
        categoria: 'categoria3',
        año: 2021,
        id: 6,
    },

    {
        img: 'img/libro7.jpg',
        nombre: 'The Chronicles Of Narnia',
        autor: 'C.S. Lewis',
        Precio: 50,
        idioma: 'español',
        categoria: 'categoria4',
        año: 2022,
        id: 7,
    },

    {
        img: 'img/libro8.jpg',
        nombre: 'Frankenstein',
        autor: 'Mary Shelley',
        Precio: 46,
        idioma: 'ingles',
        categoria: 'categoria4',
        año: 2022,
        id: 8,
    },

    {
        img: 'img/libro9.jpg',
        nombre: 'The Darkening Age',
        autor: 'Catherine Nixey',
        Precio: 21,
        idioma: 'español',
        categoria: 'categoria4',
        año: 2023,
        id: 9,
    },

    {
        img: 'img/libro10.jpg',
        nombre: 'The Iliad And The Odyssey',
        autor: 'Homer',
        Precio: 35,
        idioma: 'ingles',
        categoria: 'categoria1',
        año: 2024,
        id: 10,
    },

    {
        img: 'img/libro11.jpg',
        nombre: 'The Little Book Of Hygge',
        autor: 'Meik Wiking',
        Precio: 10,
        idioma: 'ingles',
        categoria: 'categoria5',
        año: 2022,
        id: 11,
    },

    {
        img: 'img/libro12.jpg',
        nombre: 'The First New Universe',
        autor: 'Heidi Priebe',
        Precio: 15,
        categoria: 'categoria2',
        año: 2021,
        id: 12,
    },

    {
        img: 'img/libro13.jpg',
        nombre: 'Your Heart Is The Sea',
        autor: 'Nikita Gill',
        Precio: 26,
        idioma: 'español',
        categoria: 'categoria2',
        año: 2024,
        id: 13,
    },

    {
        img: 'img/libro14.jpg',
        nombre: 'You Are Not A Princess(Abd thats OK!)',
        autor: 'Melanie Berliet',
        Precio: 12,
        idioma: 'ingles',
        categoria: 'categoria5',
        año: 2023,
        id: 14,
    },

    {
        img: 'img/libro15.jpg',
        nombre: 'The Picture Of Dorian Gray',
        autor: 'Oscar Wilde',
        Precio: 48,
        idioma: 'ingles',
        categoria: 'categoria4',
        año: 2021,
        id: 15,
    },

    {
        img: 'img/libro16.jpg',
        nombre: 'Dracula',
        autor: 'Bram Stoker',
        Precio: 55,
        idioma: 'ingles',
        categoria: 'categoria1',
        año: 2022,
        id: 16,
    },

    {
        img: 'img/libro17.jpg',
        nombre: 'Ades Adventures',
        autor: 'Alice Walker',
        Precio: 20,
        idioma: 'español',
        categoria: 'categoria5',
        año: 2021,
        id: 17,

    },

    {
        img: 'img/libro18.jpg',
        nombre: 'Crime and Punishment',
        autor: 'Fyodor Dostevsky',
        Precio: 52,
        idioma: 'ingles',
        categoria: 'categoria4',
        año: 2024,
        id: 18,
    },

    {
        img: 'img/libro19.jpg',
        nombre: 'A New Testament Biblical',
        autor: 'G.K. Beale',
        Precio: 40,
        idioma: 'ingles',
        categoria: 'categoria3',
        año: 2023,
        id: 19,
    },
]